### ISSUE TITLE
The CLASSES_ROOT generation doesn't work

### ISSUE THREAD

**Issue by sm4** [fedelopez/gta-idea-plugin#6]
When I leave the checkbox unchecked, the GTASettings.txt doesn't not get updated at all. When I put:

$MODULE_DIR$\build\classes\gta

it generates:

CLASSES_ROOT=$MODULE_DIR$\\build\\classes\\gta

**Comment by fedelopez** [comment]
The release pointed to an interim version, I fixed the download url - sorry about that.
